version: 2
updates:
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
