"""GENERATED by scripts/derive_recording_rates.py -- do not edit by hand.

De Graaf surveillance anchors for the selection model, derived by working back
from estimated DS prevalence (data/reference/ds_prevalence_ethnicity_2000_2023.csv)
through livebirth counts:
    true = prevalence/1e4 * births;  s = recorded_DS / true.

S_RACE_YEAR_*  -- recording-rate s(race, year) prior (logit mean/sigma; idx 5
  Unknown and idx 6 NH Multi-race = weak fallback s=0.4).
PREV_RACE_YEAR / _SIGMA -- de Graaf TRUE prevalence per 10k (mean/sigma) used as
  the full-margin target that ties the model's N-weighted marginal p_ds_lb per
  race x year to surveillance; idx 5 Unknown and idx 6 Multi-race have no target
  (NaN -> not anchored).

Rows = race idx 0..6; columns = years 2016-2024. 2019-2024 prevalence
is imputed (survival ratio held flat; see the script), so sigma widens across the
tail. Regenerate after a data refresh or when surveillance years fill in.

The idx-6 NH Multi-race row is the deterministic UNKNOWN_S fallback (de Graaf has no
multi-race category); it was added when multi-race was promoted to its own group and
will be re-emitted identically on the next regeneration.
"""

from __future__ import annotations

import numpy as np

ANCHOR_YEARS = (2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024)

S_RACE_YEAR_LOGIT = np.array([
    [ -0.1545,  -0.2576,  -0.1885,  -0.1812,  -0.2747,  -0.4535,  -0.4940,  -0.4929,  -0.4765],  # NH White
    [ -0.6107,  -0.7640,  -0.7826,  -1.0124,  -0.7627,  -0.9192,  -0.8537,  -0.8929,  -0.9973],  # NH Black
    [  0.7024,   0.1491,   1.1011,  -0.5327,   0.1182,   0.3739,   1.1275,   0.6233,  -0.1885],  # NH AIAN
    [ -0.5549,  -0.6742,  -0.4897,  -0.5650,  -1.0188,  -0.8664,  -0.6013,  -0.7967,  -1.0455],  # NH Asian/Pacific Islander
    [ -0.5139,  -0.4962,  -0.4468,  -0.5159,  -0.5762,  -0.5756,  -0.7883,  -0.7363,  -0.7119],  # Hispanic
    [ -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055],  # Unknown
    [ -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055,  -0.4055],  # NH Multi-race
])

S_RACE_YEAR_SIGMA = np.array([
    [  0.1404,   0.2193,   0.1389,   0.2535,   0.3041,   0.3393,   0.3899,   0.4461,   0.5052],  # NH White
    [  0.1449,   0.2000,   0.1389,   0.2072,   0.2671,   0.3024,   0.3548,   0.3989,   0.4349],  # NH Black
    [  0.6286,   0.5286,   0.7519,   0.5000,   0.6177,   0.7442,   1.2670,   0.9970,   0.7376],  # NH AIAN
    [  0.1977,   0.2455,   0.2049,   0.2710,   0.2933,   0.3411,   0.4090,   0.4341,   0.4518],  # NH Asian/Pacific Islander
    [  0.1309,   0.2046,   0.1333,   0.2258,   0.2740,   0.3272,   0.3549,   0.4116,   0.4663],  # Hispanic
    [  0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000],  # Unknown
    [  0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000,   0.5000],  # NH Multi-race
])

PREV_RACE_YEAR = np.array([
    [ 12.6404,  12.6284,  12.6476,  12.8923,  13.1392,  13.4337,  13.7065,  13.8894,  14.1257],  # NH White
    [ 12.4245,  12.7042,  13.1720,  13.3464,  13.8979,  14.3758,  15.1450,  15.7261,  16.2653],  # NH Black
    [ 10.7420,  11.8747,  13.0528,  12.3548,  12.6795,  12.9325,  13.3929,  13.7683,  13.7981],  # NH AIAN
    [  9.1007,   9.0369,   8.8714,   9.0640,   9.3922,   9.6860,  10.1167,  10.2674,  10.3753],  # NH Asian/Pacific Islander
    [ 15.9960,  16.4067,  16.7694,  16.8666,  17.0503,  17.1714,  17.4614,  17.5815,  17.4380],  # Hispanic
    [  np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan],  # Unknown
    [  np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan],  # NH Multi-race
])

PREV_RACE_YEAR_SIGMA = np.array([
    [  0.8848,   1.5154,   0.8853,   1.7405,   2.2337,   2.7539,   3.2895,   3.8196,   4.3790],  # NH White
    [  0.8697,   1.5245,   0.9220,   1.8018,   2.3626,   2.9470,   3.6348,   4.3247,   5.0422],  # NH Black
    [  0.7519,   1.4250,   0.9137,   1.6679,   2.1555,   2.6512,   3.2143,   3.7863,   4.2774],  # NH AIAN
    [  0.6371,   1.0844,   0.6210,   1.2236,   1.5967,   1.9856,   2.4280,   2.8235,   3.2164],  # NH Asian/Pacific Islander
    [  1.1197,   1.9688,   1.1739,   2.2770,   2.8985,   3.5201,   4.1907,   4.8349,   5.4058],  # Hispanic
    [  np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan],  # Unknown
    [  np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan,   np.nan],  # NH Multi-race
])
